
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program_File/C_C++_Develop/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:28 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
